export const ROOT = 'http://46.226.160.59:8080/api';
export const ACCOUNT = `${ROOT}/account`;
export const ACCOUNT_APPROVE = (id: string) => `${ACCOUNT}/${id}/approve`;
export const ACCOUNT_REJECT = (id: string) => `${ACCOUNT}/${id}/reject`;
export const REGISTRATION_STATUS = `${ACCOUNT}/registration-status`;
export const KEYS = `${ROOT}/key`;
export const USERS = `${ROOT}/user`;
export const CONSIDERATION = `${ACCOUNT}/consideration`;
export const LOGIN = `${ACCOUNT}/login`;
export const PROFILE = `${ACCOUNT}/profile`;
export const REQUEST = `${ROOT}/request`;
export const KEY_APPROVE = (id: string) => `${REQUEST}/${id}/approve`;
export const KEY_REJECT = (id: string) => `${REQUEST}/${id}/reject`;
export const OVERLAPPING = (id: string) => `${REQUEST}/${id}/overlapping`;
export const USER_ROLE = `${ACCOUNT}/role`;
export const EDIT_USER_ROLE = (id: string) => `${ACCOUNT}/${id}/role`;
